---
name: Create Boutiques descriptor

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:

  create-descriptor:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.x

    - name: Install package
      run: |
        pip install -U pip
        pip install .

    - name: Create descriptor for dummy-cli
      uses: michellewang/argparse-to-boutiques@c0edd14ff097e03f6eb1f319bd4ae665a157612c
      with:
        parser-type: argparse
        parser-location: my_tool.cli:get_parser
        output-path: my_tool/data/descriptor-dummy-cli.json
        updates-file: descriptor_updates.json
        updates-str: '{"description": "This is a custom description set via updates-str"}'
        token: ${{ secrets.PAT }}
        exclude-version: true
        open-pr: true

    - name: Create descriptor for dummy-cli-click
      uses: michellewang/argparse-to-boutiques@c0edd14ff097e03f6eb1f319bd4ae665a157612c
      with:
        parser-type: click
        parser-location: my_tool.cli_click:main
        output-path: my_tool/data/descriptor-dummy-cli-click.json
        token: ${{ secrets.PAT }}
        exclude-version: true
        open-pr: true
        click-prog-name: dummy-cli-click

    - name: Create descriptor for dummy-cli-click-group
      uses: michellewang/argparse-to-boutiques@c0edd14ff097e03f6eb1f319bd4ae665a157612c
      with:
        parser-type: click
        parser-location: my_tool.cli_click_group:group
        output-path: my_tool/data/descriptor-dummy-cli-click-group.json
        token: ${{ secrets.PAT }}
        exclude-version: true
        open-pr: true
        click-prog-name: dummy-cli-click-group

    - name: Create descriptor for dummy-cli-click-group greet
      uses: michellewang/argparse-to-boutiques@c0edd14ff097e03f6eb1f319bd4ae665a157612c
      with:
        parser-type: click
        parser-location: my_tool.cli_click_group:greet
        output-path: my_tool/data/descriptor-dummy-cli-click-group.json
        token: ${{ secrets.PAT }}
        exclude-version: true
        open-pr: true
        click-prog-name: dummy-cli-click-group
        click-parent-location: my_tool.cli_click_group:group
