---
name: Create Boutiques descriptor

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:

  create-descriptor:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v6

    - uses: actions/setup-python@v6

    - name: Install package
      run: |
        pip install -U pip
        pip install .

    - name: Create descriptor
      uses: michellewang/argparse-to-boutiques@03b2f06d26cec75ef296a6408737675d94db40a2
      with:
        location: my_tool.cli
        parser: get_parser
        # parser-location: my_tool.cli:get_parser
        output-path: my_tool/data/descriptor.json
