---
name: Run tests

on:
  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v6

    - uses: actions/setup-python@v6

    - name: Install package
      run: |
        pip install -U pip
        pip install .

    - name: Upload coverage to Codecov
      uses: michellewang/argparse-to-boutiques
      with:
        parser-location: my_tool.cli:get_parser
        output-path: my_tool/data/descriptor.json
